"use client";

import { useEffect, useMemo, useState } from "react";

type Deal = { id:string; location:string; year:number; brand:string; model:string; trim:string; msrp:number; monthlyPayment:number; termMonths:number; dueUpfront:number; milesPerYear:number|null; expires:string|null; sourceUrl:string; imageUrl:string|null; incentive:string|null; rebateMonthly:number|null };
type Range = { min:number; max:number };
type Preferences = { msrp:Range; monthly:Range; upfront:Range; miles:Range; brands:string[]; models:string[]; trims:string[]; region:string };
type CompareChoice = { id:string; brand:string; model:string; trim:string };

const limit=1_000_000;
const defaults:Preferences={msrp:{min:0,max:limit},monthly:{min:0,max:limit},upfront:{min:0,max:limit},miles:{min:0,max:limit},brands:[],models:[],trims:[],region:"All locations"};
const allBrands=["Acura","Alfa Romeo","Audi","BMW","Buick","Cadillac","Chevrolet","Chrysler","Dodge","Ford","Genesis","GMC","Honda","Hyundai","INFINITI","Jaguar","Jeep","Kia","Land Rover","Lexus","Lincoln","Lucid","Maserati","Mazda","Mercedes-Benz","MINI","Mitsubishi","Nissan","Polestar","Porsche","RAM","Rivian","Subaru","Tesla","Toyota","Volkswagen","Volvo"];
const sep="␟";
const modelId=(brand:string,model:string)=>brand+sep+model;
const trimId=(brand:string,model:string,trim:string)=>modelId(brand,model)+sep+trim;
const money=(n:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(n);
const score=(d:Pick<Deal,"dueUpfront"|"termMonths"|"monthlyPayment"|"msrp">)=>(((d.dueUpfront-d.monthlyPayment)/d.termMonths+d.monthlyPayment)/d.msrp)*100;

export default function Home(){
 const [deals,setDeals]=useState<Deal[]>([]);
 const [preferences,setPreferences]=useState<Preferences>(defaults);
 const [loading,setLoading]=useState(true);
 const [error,setError]=useState("");
 const [updatedAt,setUpdatedAt]=useState<string|null>(null);
 const [filtersOpen,setFiltersOpen]=useState(false);
 const [checkOpen,setCheckOpen]=useState(false);
 const [compareOpen,setCompareOpen]=useState(false);
 const [compareView,setCompareView]=useState(false);
 const [compareChoices,setCompareChoices]=useState<CompareChoice[]>([]);
 const [compareDraft,setCompareDraft]=useState({brand:"",model:"",trim:""});
 const [shown,setShown]=useState(10);
 const [showFloatingFilters,setShowFloatingFilters]=useState(false);
 const [check,setCheck]=useState({msrp:"",upfront:"",monthly:"",term:"36"});
 const refresh=async()=>{setLoading(true);setError("");try{const r=await fetch("/api/deals",{cache:"no-store"}),p=await r.json();if(!r.ok)throw Error(p.error||"Leasehackr could not be reached.");setDeals(p.deals);setUpdatedAt(p.fetchedAt)}catch(e){setError(e instanceof Error?e.message:"Could not refresh the offers.")}finally{setLoading(false)}};
 useEffect(()=>{refresh();const onScroll=()=>setShowFloatingFilters(window.scrollY>260);window.addEventListener("scroll",onScroll,{passive:true});return()=>window.removeEventListener("scroll",onScroll)},[]);
 const selected=useMemo(()=>deals.filter(d=>d.msrp>=preferences.msrp.min&&d.msrp<=preferences.msrp.max&&d.monthlyPayment>=preferences.monthly.min&&d.monthlyPayment<=preferences.monthly.max&&d.dueUpfront>=preferences.upfront.min&&d.dueUpfront<=preferences.upfront.max&&!!d.milesPerYear&&d.milesPerYear>=preferences.miles.min&&d.milesPerYear<=preferences.miles.max&&(!preferences.brands.length||preferences.brands.includes(d.brand))&&(!preferences.models.length||preferences.models.includes(modelId(d.brand,d.model)))&&(!preferences.trims.length||preferences.trims.includes(trimId(d.brand,d.model,d.trim)))&&(preferences.region==="All locations"||d.location.split(" - ")[0]===preferences.region)).sort((a,b)=>score(a)-score(b)),[deals,preferences]);
 const stateDeals=preferences.region==="All locations"?deals:deals.filter(d=>d.location.split(" - ")[0]===preferences.region);
 const regions=["All locations",...Array.from(new Set(deals.map(d=>d.location.split(" - ")[0]))).sort()];
 const best=selected[0],visible=selected.slice(0,shown);
 const time=updatedAt?new Intl.DateTimeFormat("en-US",{hour:"numeric",minute:"2-digit"}).format(new Date(updatedAt)):"—";
 const parsed={msrp:+check.msrp,dueUpfront:+check.upfront,monthlyPayment:+check.monthly,termMonths:+check.term};
 const checkScore=parsed.msrp&&parsed.monthlyPayment&&parsed.termMonths?score(parsed):null;
 const percentile=checkScore?Math.round(deals.filter(d=>score(d)>=checkScore).length/deals.length*100):null;
 const draftModels=Array.from(new Set(deals.filter(d=>d.brand===compareDraft.brand).map(d=>d.model))).sort();
 const draftTrims=Array.from(new Set(deals.filter(d=>d.brand===compareDraft.brand&&d.model===compareDraft.model).map(d=>d.trim))).sort();
 const compared=compareChoices.map(c=>{const inState=preferences.region==="All locations"?deals:deals.filter(d=>d.location.split(" - ")[0]===preferences.region);const offer=inState.filter(d=>d.brand===c.brand&&d.model===c.model&&d.trim===c.trim).sort((a,b)=>score(a)-score(b))[0];return {...c,offer}}).sort((a,b)=>(a.offer?score(a.offer):Infinity)-(b.offer?score(b.offer):Infinity));
 const updateRange=(field:"msrp"|"monthly"|"upfront"|"miles",part:keyof Range,value:string)=>setPreferences(p=>({...p,[field]:{...p[field],[part]:Math.max(0,+value||0)}}));
 const chooseBrands=(brands:string[])=>{setPreferences(p=>({...p,brands,models:p.models.filter(id=>brands.some(brand=>id.startsWith(brand+sep))),trims:p.trims.filter(id=>brands.some(brand=>id.startsWith(brand+sep)))}));setShown(10)};
 const addCompare=()=>{if(!compareDraft.brand||!compareDraft.model||!compareDraft.trim)return;const id=compareDraft.brand+"|"+compareDraft.model+"|"+compareDraft.trim;if(!compareChoices.some(c=>c.id===id))setCompareChoices(c=>[...c,{...compareDraft,id}])};
 if(compareView)return <ComparePage compared={compared} region={preferences.region} onBack={()=>setCompareView(false)} onEdit={()=>{setCompareView(false);setCompareOpen(true)}}/>;
 return <main className="app-shell">
  <header className="topbar"><div><p className="eyebrow">Live Leasehackr analysis</p><h1>Lease Scout</h1></div><label className="header-region">State<select value={preferences.region} onChange={e=>{setPreferences({...preferences,region:e.target.value});setShown(10)}}>{regions.map(r=><option key={r}>{r}</option>)}</select></label></header>
<aside className="score-notice" style={{margin:"20px 0 0",padding:"12px 14px",borderLeft:"3px solid #14784a",borderRadius:10,background:"#edf5ef",fontSize:12,lineHeight:1.45}}><div style={{display:"flex",alignItems:"center",gap:8,fontSize:14,fontWeight:800,color:"#075334"}}><span>Score =</span><span style={{display:"inline-flex",flexDirection:"column",alignItems:"center",minWidth:235,lineHeight:1.15}}><span style={{padding:"0 5px 3px",borderBottom:"1.5px solid currentColor"}}>(((upfront − monthly) / term) + monthly)</span><span style={{paddingTop:3}}>MSRP</span></span></div><span style={{display:"block",marginTop:7}}>Recommendation: lower is better. Under 1% is generally a solid deal; above 1.2% is usually not competitive. Score is for reference only; please use your own judgment when making a decision.</span></aside>
  <section className="intro"><div><span className="live-dot"/>Live public offers</div><p>Updated {time}</p></section>
  <section className="hero">{best?.imageUrl&&<img src={best.imageUrl} alt=""/>}<div><p>Best score</p><strong>{best?score(best).toFixed(2)+"%":"—"}</strong><span>{best?best.year+" "+best.brand+" "+best.model+" · "+money(best.monthlyPayment)+"/mo":"Adjust filters to find a match"}</span>{best&&<small>MSRP {money(best.msrp)} · Upfront {money(best.dueUpfront)} · {best.termMonths} months</small>}</div></section>
  <section className="summary"><div><b>{stateDeals.length}</b><span>{preferences.region==="All locations"?"Deals investigated":preferences.region+" deals"}</span></div><button onClick={()=>setCheckOpen(true)}><b>Check a deal</b><span>Compare your offer</span></button></section>
  <section className="toolbar"><div><h2>Best deals</h2><p>Ranked by best score · {selected.length} matches</p></div><div className="toolbar-actions"><button className="outline" onClick={()=>setCompareOpen(true)}>Compare{compareChoices.length?" ("+compareChoices.length+")":""}</button><button className="outline" onClick={()=>setFiltersOpen(true)}>Filters</button></div></section>
  {error&&<div className="notice"><b>Refresh paused.</b> {error} <button onClick={refresh}>Try again</button></div>}
  <section className="deals">{loading&&!deals.length&&<div className="loading">Loading current Leasehackr offers…</div>}{!loading&&!visible.length&&!error&&<div className="empty">No offers fit the current filters.</div>}{visible.map((d,i)=><DealCard deal={d} index={i} key={d.id}/>)}{visible.length<selected.length&&<button className="load-more" onClick={()=>setShown(n=>n+10)}>Load 10 more <span>{selected.length-visible.length} remaining</span></button>}</section>
  <div className={"bottom-actions "+(showFloatingFilters?"visible":"")}><button className="primary" onClick={()=>setFiltersOpen(true)}>Filters <span>{selected.length}</span></button></div>
{filtersOpen&&<div className="sheet-backdrop" onMouseDown={()=>setFiltersOpen(false)}><section className="sheet" role="dialog" aria-modal="true" onMouseDown={e=>e.stopPropagation()}><div className="handle"/><div className="sheet-top"><div><h2>Filters</h2><p>Refine the selected state’s live offers.</p></div><button onClick={()=>setFiltersOpen(false)}>×</button></div><section className="filter-section"><h3 style={{margin:"10px 0 14px",fontSize:16}}>Filter by model</h3><VehicleFilters deals={deals} preferences={preferences} setPreferences={setPreferences} chooseBrands={chooseBrands} onChanged={()=>setShown(10)}/></section><section className="filter-section price-section" style={{marginTop:32,paddingTop:22,borderTop:"1px solid #dce5de"}}><h3 style={{margin:"0 0 14px",fontSize:16}}>Filter by price &amp; lease terms</h3><div className="range-fields">{([["msrp","MSRP",200000,1000],["monthly","Monthly payment",2500,25],["upfront","Upfront payment",15000,100],["miles","Expected miles / year",30000,500]] as const).map(([key,label,max,step])=>{const min=preferences[key].min,upper=preferences[key].max===limit?max:preferences[key].max;return <fieldset key={key}><legend>{label}</legend><div className="slider-label"><span>{min.toLocaleString()}</span><span>{preferences[key].max===limit?"Any":upper.toLocaleString()}</span></div><div className="dual-slider"><div className="slider-fill" style={{left:min/max*100+"%",right:100-upper/max*100+"%"}}/><input aria-label={label+" minimum"} type="range" min="0" max={max} step={step} value={min} onChange={e=>updateRange(key,"min",String(Math.min(+e.target.value,upper)))}/><input aria-label={label+" maximum"} type="range" min="0" max={max} step={step} value={upper} onChange={e=>updateRange(key,"max",String(Math.max(+e.target.value,min)))}/></div></fieldset>})}</div></section><div className="sheet-actions"><button onClick={()=>{setPreferences(defaults);setShown(10)}}>Reset</button><button className="apply" onClick={()=>setFiltersOpen(false)}>Show {selected.length} deals</button></div></section></div>}
  {checkOpen&&<div className="sheet-backdrop" onMouseDown={()=>setCheckOpen(false)}><section className="sheet checker" role="dialog" aria-modal="true" onMouseDown={e=>e.stopPropagation()}><div className="handle"/><div className="sheet-top"><div><h2>External deal check</h2><p>Enter an offer to calculate its score and compare it with the current investigation.</p></div><button onClick={()=>setCheckOpen(false)}>×</button></div><div className="check-grid">{([["msrp","MSRP"],["upfront","Upfront payment"],["monthly","Monthly payment"],["term","Term (months)"]] as const).map(([key,label])=><label key={key}>{label}<input type="number" inputMode="numeric" value={check[key]} onChange={e=>setCheck({...check,[key]:e.target.value})}/></label>)}</div>{checkScore&&<div className="check-result"><span>Your score</span><b>{checkScore.toFixed(2)}%</b><p>This scores better than {percentile}% of the {deals.length} live offers currently investigated.</p></div>}<button className="apply" onClick={()=>setCheckOpen(false)}>Done</button></section></div>}
  {compareOpen&&<div className="sheet-backdrop" onMouseDown={()=>setCompareOpen(false)}><section className="sheet compare-picker" role="dialog" aria-modal="true" onMouseDown={e=>e.stopPropagation()}><div className="handle"/><div className="sheet-top"><div><h2>Compare cars</h2><p>Build a short list of exact brand, model, and trim choices.</p></div><button onClick={()=>setCompareOpen(false)}>×</button></div><label className="select-label">Brand<select value={compareDraft.brand} onChange={e=>setCompareDraft({brand:e.target.value,model:"",trim:""})}><option value="">Choose a brand</option>{allBrands.map(b=><option key={b}>{b}</option>)}</select></label><label className="select-label">Model<select disabled={!compareDraft.brand} value={compareDraft.model} onChange={e=>setCompareDraft(d=>({...d,model:e.target.value,trim:""}))}><option value="">Choose a model</option>{draftModels.map(m=><option key={m}>{m}</option>)}</select></label><label className="select-label">Trim<select disabled={!compareDraft.model} value={compareDraft.trim} onChange={e=>setCompareDraft(d=>({...d,trim:e.target.value}))}><option value="">Choose a trim</option>{draftTrims.map(t=><option key={t}>{t}</option>)}</select></label><button className="add-choice" disabled={!compareDraft.trim} onClick={addCompare}>Add to comparison</button>{compareChoices.length>0&&<div className="choice-list">{compareChoices.map(c=><div key={c.id}><span>{c.brand} {c.model}<small>{c.trim}</small></span><button onClick={()=>setCompareChoices(items=>items.filter(x=>x.id!==c.id))}>×</button></div>)}</div>}<button className="apply compare-go" disabled={!compareChoices.length} onClick={()=>{setCompareOpen(false);setCompareView(true)}}>Compare {compareChoices.length||""} car{compareChoices.length===1?"":"s"}</button></section></div>}
 </main>
}

function VehicleFilters({deals,preferences,setPreferences,chooseBrands,onChanged}:{deals:Deal[];preferences:Preferences;setPreferences:React.Dispatch<React.SetStateAction<Preferences>>;chooseBrands:(brands:string[])=>void;onChanged:()=>void}){
 return <div className="vehicle-filters"><MultiPicker label="Brand" empty="All brands" options={allBrands} value={preferences.brands} onChange={chooseBrands}/>{preferences.brands.map(brand=>{const prefix=brand+sep,models=Array.from(new Set(deals.filter(d=>d.brand===brand).map(d=>d.model))).sort(),activeModels=preferences.models.filter(id=>id.startsWith(prefix)),modelLabels=Object.fromEntries(models.map(m=>[modelId(brand,m),m]));return <div className="brand-filter" key={brand}><p className="brand-heading">{brand}</p><MultiPicker label="Model" empty={"All "+brand+" models"} options={models.map(m=>modelId(brand,m))} labels={modelLabels} value={activeModels} onChange={next=>{setPreferences(p=>({...p,models:[...p.models.filter(id=>!id.startsWith(prefix)),...next],trims:p.trims.filter(id=>!id.startsWith(prefix)||next.some(model=>id.startsWith(model+sep)))}));onChanged()}}/>{activeModels.map(active=>{const model=active.split(sep)[1],trimPrefix=active+sep,trims=Array.from(new Set(deals.filter(d=>d.brand===brand&&d.model===model).map(d=>d.trim))).sort(),trimLabels=Object.fromEntries(trims.map(t=>[trimId(brand,model,t),t]));return <MultiPicker key={active} label={"Trim · "+model} empty={"All "+model+" trims"} options={trims.map(t=>trimId(brand,model,t))} labels={trimLabels} value={preferences.trims.filter(id=>id.startsWith(trimPrefix))} onChange={next=>{setPreferences(p=>({...p,trims:[...p.trims.filter(id=>!id.startsWith(trimPrefix)),...next]}));onChanged()}}/>})}</div>})}</div>
}

function DealCard({deal,index}:{deal:Deal;index:number}){const rebateScore=deal.rebateMonthly?score({...deal,monthlyPayment:deal.rebateMonthly}):null;return <article className="deal"><div className="rank">#{index+1}</div>{deal.imageUrl&&<img className="car" src={deal.imageUrl} alt={deal.year+" "+deal.brand+" "+deal.model}/>}<div className="deal-copy"><p className="location">{deal.location}{deal.expires?" · Expires "+deal.expires:""}</p><h3>{deal.year} {deal.brand} {deal.model}</h3><p className="trim">{deal.trim}</p></div><div className="score"><b>{score(deal).toFixed(2)}%</b><span>score</span>{rebateScore&&<><b className="rebate-score">{rebateScore.toFixed(2)}%</b><span className="rebate-label">with rebate</span></>}</div><div className="deal-data"><div><span>MSRP</span><b>{money(deal.msrp)}</b></div><div><span>MONTHLY</span><b>{money(deal.monthlyPayment)}</b></div><div><span>UPFRONT</span><b>{money(deal.dueUpfront)}</b></div><div><span>TERM</span><b>{deal.termMonths} mo</b></div></div>{deal.incentive&&<p className="incentive">Conditional offer: {deal.incentive}</p>}<div className="deal-footer"><span>{deal.milesPerYear?deal.milesPerYear.toLocaleString()+" mi/yr":"Mileage varies"}</span><a href={deal.sourceUrl} target="_blank" rel="noreferrer">Leasehackr ↗</a></div></article>}

function ComparePage({compared,region,onBack,onEdit}:{compared:Array<CompareChoice&{offer:Deal|undefined}>;region:string;onBack:()=>void;onEdit:()=>void}){const max=Math.max(...compared.map(c=>c.offer?c.offer.monthlyPayment+c.offer.dueUpfront/c.offer.termMonths:0),1);return <main className="app-shell compare-page"><header className="compare-header"><button className="back" onClick={onBack}>← Deals</button><button className="outline" onClick={onEdit}>Edit cars</button></header><p className="eyebrow">Live Leasehackr comparison</p><h1>Compare prices</h1><p className="compare-subtitle">Best current {region==="All locations"?"US ":""}offers for each selected trim, sorted by lease score.</p>{!compared.length?<div className="empty">Choose at least one car to begin comparing.</div>:<section className="cost-chart"><h2>Estimated monthly outlay</h2><p>Current Leasehackr offers, sorted by score. Outlay spreads the upfront payment over the lease term.</p>{compared.map(c=>{const outlay=c.offer?c.offer.monthlyPayment+c.offer.dueUpfront/c.offer.termMonths:0;return <div className="chart-row" key={c.id}><div className="chart-copy"><b>{c.brand} {c.model}</b><span>{c.trim}</span><small>{c.offer?.location||"No live deal"}</small></div>{c.offer?<div className="chart-detail"><i><em style={{width:outlay/max*100+"%"}}/></i><span>Live {money(c.offer.monthlyPayment)}/mo · Score {score(c.offer).toFixed(2)}% · MSRP {money(c.offer.msrp)} · Upfront {money(c.offer.dueUpfront)}</span></div>:<strong className="no-offer">No live deal</strong>}{c.offer&&<strong>{money(Math.round(outlay))}/mo</strong>}</div>})}</section>}</main>}

function MultiPicker({label,empty,options,labels,value,onChange}:{label:string;empty:string;options:string[];labels?:Record<string,string>;value:string[];onChange:(next:string[])=>void}){const show=(item:string)=>labels?.[item]||item,summary=value.length?(value.length===1?show(value[0]):value.length+" selected"):empty;return <details className="multi-picker"><summary><span>{label}</span><b>{summary}</b></summary><div className="picker-options">{options.map(option=>{const active=value.includes(option);return <button type="button" className={active?"chosen":""} key={option} onClick={()=>onChange(active?value.filter(item=>item!==option):[...value,option])}>{active?"✓ ":""}{show(option)}</button>})}</div></details>}
