"use client";
import { useEffect, useMemo, useState } from "react";

type Deal = { id:string; location:string; year:number; brand:string; model:string; trim:string; msrp:number; monthlyPayment:number; termMonths:number; dueUpfront:number; milesPerYear:number|null; expires:string|null; sourceUrl:string; imageUrl:string|null; incentive:string|null; rebateMonthly:number|null };
type Range = { min:number; max:number };
type Preferences = { msrp:Range; monthly:Range; upfront:Range; miles:Range; brands:string[]; models:string[]; trims:string[]; region:string };
type CompareChoice = { id:string; brand:string; model:string; trim:string };
const limit = 1_000_000, defaults:Preferences = { msrp:{min:0,max:limit}, monthly:{min:0,max:limit}, upfront:{min:0,max:limit}, miles:{min:0,max:limit}, brands:[], models:[], trims:[], region:"All locations" };
const allBrands = ["Acura","Alfa Romeo","Audi","BMW","Buick","Cadillac","Chevrolet","Chrysler","Dodge","Ford","Genesis","GMC","Honda","Hyundai","INFINITI","Jaguar","Jeep","Kia","Land Rover","Lexus","Lincoln","Lucid","Maserati","Mazda","Mercedes-Benz","MINI","Mitsubishi","Nissan","Polestar","Porsche","RAM","Rivian","Subaru","Tesla","Toyota","Volkswagen","Volvo"];
const money=(n:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(n);
const score=(d:Pick<Deal,"dueUpfront"|"termMonths"|"monthlyPayment"|"msrp">)=>((d.dueUpfront/d.termMonths+d.monthlyPayment)/d.msrp)*100;
const choiceId=(brand:string,model:string,trim:string)=>`${brand}|${model}|${trim}`;
const brandAssist:Record<string,string>={"Hyundai":"SmartSense",Kia:"Drive Wise",Toyota:"Toyota Safety Sense",Honda:"Honda Sensing",Mazda:"i-Activsense",GMC:"GMC Pro Safety",Chevrolet:"Chevy Safety Assist","Mercedes-Benz":"Driver Assistance Package"};
function roughSpecs(brand:string,model:string,trim:string){
 const name=model.toLowerCase();
 const trimName=trim.toLowerCase();
 if(brand==="Hyundai"&&/ioniq 5/.test(name)){
  const limited=/limited/.test(trimName),awd=/awd/.test(trimName);
  return {engine:"Battery electric",epa:awd?(limited?"269 mi EPA est.":"290 mi EPA est."):"318 mi EPA est.",hp:awd?"320 hp":"225 hp",seats:"5",hud:limited?"Standard":"Not listed",audio:limited?"Bose Premium Audio":"Standard audio (Bose unavailable)",blindSpot:limited?"BVM standard":"Blind-Spot Collision Warning",assist:"SmartSense",sourceLabel:"Hyundai 2026 IONIQ 5",sourceUrl:"https://www.hyundaiusa.com/us/en/vehicles/ioniq-5/compare-specs"};
 }
 if(brand==="GMC"&&/hummer ev suv/.test(name)&&/2x/.test(trimName))return {engine:"Battery electric · dual-motor e4WD",epa:"319 mi GM est.",hp:"570 hp GM est.",seats:"5",hud:"Not listed",audio:"Bose 14-speaker surround",blindSpot:"Blind Zone Steering Assist",assist:"Super Cruise available",sourceLabel:"GMC 2026 HUMMER EV SUV 2X",sourceUrl:"https://www.gmc.com/electric/hummer-ev/suv"};
 if(brand==="Acura"&&/integra/.test(name)&&/a-spec/.test(trimName))return {engine:"1.5L VTEC turbo I-4",epa:"32 mpg EPA combined",hp:"200 hp",seats:"5",hud:"Technology Package only",audio:"Acura Premium Audio · 8 speakers",blindSpot:"Not listed for A-Spec",assist:"AcuraWatch: ACC, LKAS, CMBS",sourceLabel:"Acura 2026 Integra fact sheet",sourceUrl:"https://www.acura.com/-/media/Files/Vehicles/INTEGRA/2026/v2/Acura_2026_Integra_Fact-Sheet.pdf"};
 const known=[
  [/ioniq 5/,"Battery electric","168–320 hp","Bose available","SmartSense"],
  [/ioniq 9/,"Battery electric","215–422 hp","Bose available","SmartSense"],
  [/ev6/,"Battery electric","167–641 hp","Meridian available","Drive Wise"],
  [/prologue/,"Battery electric","220–300 hp","Bose available","Honda Sensing"],
  [/cx-90 phev|cx-70 phev/,"Plug-in hybrid","323 hp","Bose available","i-Activsense"],
  [/tacoma/,"Turbocharged gas / hybrid available","228–326 hp","JBL available","Toyota Safety Sense"],
  [/tundra/,"Twin-turbo V6 / hybrid available","358–437 hp","JBL available","Toyota Safety Sense"],
  [/canyon/,"Turbocharged gas","310 hp","Bose available","GMC Pro Safety"],
  [/s 580/,"Twin-turbo V8 mild hybrid","496 hp","Burmester available","Driver Assistance Package"],
  [/bZ/,"Battery electric","221 hp","JBL available","Toyota Safety Sense"]
 ].find(([pattern])=>(pattern as RegExp).test(name)) as [RegExp,string,string,string,string]|undefined;
 return known?{engine:known[1],epa:"OEM trim sheet not yet connected",hp:known[2],seats:"OEM trim sheet not yet connected",hud:"OEM trim sheet not yet connected",audio:known[3],blindSpot:"OEM trim sheet not yet connected",assist:known[4],sourceLabel:"",sourceUrl:""}:{engine:/hybrid|phev/i.test(model)?"Hybrid powertrain":"OEM trim sheet not yet connected",epa:"OEM trim sheet not yet connected",hp:"OEM trim sheet not yet connected",seats:"OEM trim sheet not yet connected",hud:"OEM trim sheet not yet connected",audio:"OEM trim sheet not yet connected",blindSpot:"OEM trim sheet not yet connected",assist:brandAssist[brand]||"OEM trim sheet not yet connected",sourceLabel:"",sourceUrl:""};
}

export default function Home(){
 const [deals,setDeals]=useState<Deal[]>([]),[preferences,setPreferences]=useState(defaults),[loading,setLoading]=useState(true),[error,setError]=useState(""),[updatedAt,setUpdatedAt]=useState<string|null>(null),[filtersOpen,setFiltersOpen]=useState(false),[checkOpen,setCheckOpen]=useState(false),[compareOpen,setCompareOpen]=useState(false),[compareView,setCompareView]=useState(false),[compareChoices,setCompareChoices]=useState<CompareChoice[]>([]),[compareDraft,setCompareDraft]=useState({brand:"",model:"",trim:""}),[shown,setShown]=useState(10),[showFloatingFilters,setShowFloatingFilters]=useState(false),[check,setCheck]=useState({msrp:"",upfront:"",monthly:"",term:"36"});
 const refresh=async()=>{setLoading(true);setError("");try{const r=await fetch("/api/deals",{cache:"no-store"}),p=await r.json();if(!r.ok)throw Error(p.error||"Leasehackr could not be reached.");setDeals(p.deals);setUpdatedAt(p.fetchedAt)}catch(e){setError(e instanceof Error?e.message:"Could not refresh the offers.")}finally{setLoading(false)}}; useEffect(()=>{refresh();const onScroll=()=>setShowFloatingFilters(window.scrollY>260);window.addEventListener("scroll",onScroll,{passive:true});return()=>window.removeEventListener("scroll",onScroll)},[]);
 const selected=useMemo(()=>deals.filter(d=>d.msrp>=preferences.msrp.min&&d.msrp<=preferences.msrp.max&&d.monthlyPayment>=preferences.monthly.min&&d.monthlyPayment<=preferences.monthly.max&&d.dueUpfront>=preferences.upfront.min&&d.dueUpfront<=preferences.upfront.max&&!!d.milesPerYear&&d.milesPerYear>=preferences.miles.min&&d.milesPerYear<=preferences.miles.max&&(!preferences.brands.length||preferences.brands.includes(d.brand))&&(!preferences.models.length||preferences.models.includes(d.model))&&(!preferences.trims.length||preferences.trims.includes(d.trim))&&(preferences.region==="All locations"||d.location.split(" - ")[0]===preferences.region)).sort((a,b)=>score(a)-score(b)),[deals,preferences]);
 const stateDeals=preferences.region==="All locations"?deals:deals.filter(d=>d.location.split(" - ")[0]===preferences.region); const visible=selected.slice(0,shown),best=selected[0],regions=["All locations",...Array.from(new Set(deals.map(d=>d.location.split(" - ")[0]))).sort()],models=Array.from(new Set(deals.filter(d=>!preferences.brands.length||preferences.brands.includes(d.brand)).map(d=>d.model))).filter(Boolean).sort(),trims=Array.from(new Set(deals.filter(d=>(!preferences.brands.length||preferences.brands.includes(d.brand))&&(!preferences.models.length||preferences.models.includes(d.model))).map(d=>d.trim))).filter(Boolean).sort(); const time=updatedAt?new Intl.DateTimeFormat("en-US",{hour:"numeric",minute:"2-digit"}).format(new Date(updatedAt)):"—";
 const parsed={msrp:+check.msrp, dueUpfront:+check.upfront, monthlyPayment:+check.monthly, termMonths:+check.term}; const checkScore=parsed.msrp&&parsed.monthlyPayment&&parsed.termMonths?score(parsed):null; const percentile=checkScore?Math.round((deals.filter(d=>score(d)<=checkScore).length/deals.length)*100):null;
 const updateRange=(field:"msrp"|"monthly"|"upfront"|"miles",part:keyof Range,value:string)=>setPreferences(p=>({...p,[field]:{...p[field],[part]:Math.max(0,+value||0)}}));
 const draftModels=Array.from(new Set(deals.filter(d=>d.brand===compareDraft.brand).map(d=>d.model))).sort();
 const draftTrims=Array.from(new Set(deals.filter(d=>d.brand===compareDraft.brand&&d.model===compareDraft.model).map(d=>d.trim))).sort();
 const addCompareChoice=()=>{if(!compareDraft.brand||!compareDraft.model||!compareDraft.trim)return;const id=choiceId(compareDraft.brand,compareDraft.model,compareDraft.trim);if(!compareChoices.some(c=>c.id===id))setCompareChoices(c=>[...c,{...compareDraft,id}])};
 const compared=compareChoices.map(choice=>{const inState=preferences.region==="All locations"?deals:deals.filter(d=>d.location.split(" - ")[0]===preferences.region);const offer=inState.filter(d=>d.brand===choice.brand&&d.model===choice.model&&d.trim===choice.trim).sort((a,b)=>score(a)-score(b))[0];return {...choice,offer,specs:roughSpecs(choice.brand,choice.model,choice.trim)}}).sort((a,b)=>(a.offer?score(a.offer):Infinity)-(b.offer?score(b.offer):Infinity));
 if(compareView)return <ComparePage compared={compared} region={preferences.region} onBack={()=>setCompareView(false)} onEdit={()=>{setCompareView(false);setCompareOpen(true)}}/>;
 return <main className="app-shell"><header className="topbar"><div><p className="eyebrow">Live Leasehackr analysis</p><h1>Lease Scout</h1></div><label className="header-region">State<select value={preferences.region} onChange={e=>{setPreferences({...preferences,region:e.target.value});setShown(10)}}>{regions.map(r=><option key={r}>{r}</option>)}</select></label></header>
  <section className="intro"><div><span className="live-dot"/>Live public offers</div><p>Updated {time}</p></section>
  <section className="hero">{best?.imageUrl&&<img src={best.imageUrl} alt=""/>}<div><p>Best score</p><strong>{best?`${score(best).toFixed(2)}%`:"—"}</strong><span>{best?`${best.year} ${best.brand} ${best.model} · ${money(best.monthlyPayment)}/mo`:"Adjust filters to find a match"}</span>{best&&<small>MSRP {money(best.msrp)} · Upfront {money(best.dueUpfront)} · {best.termMonths} months</small>}</div></section>
  <section className="summary"><div><b>{stateDeals.length}</b><span>{preferences.region==="All locations"?"Deals investigated":`${preferences.region} deals`}</span></div><button onClick={()=>setCheckOpen(true)}><b>Check a deal</b><span>Compare your offer</span></button></section>
  <section className="toolbar"><div><h2>Best deals</h2><p>Ranked by best score · {selected.length} matches</p></div><div className="toolbar-actions"><button className="outline" onClick={()=>setCompareOpen(true)}>Compare{compareChoices.length?` (${compareChoices.length})`:""}</button><button className="outline" onClick={()=>setFiltersOpen(true)}>Filters</button></div></section>
  {error&&<div className="notice"><b>Refresh paused.</b> {error} <button onClick={refresh}>Try again</button></div>}
  <section className="deals">{loading&&!deals.length&&<div className="loading">Loading current Leasehackr offers…</div>}{!loading&&!visible.length&&!error&&<div className="empty">No offers fit the current filters.</div>}{visible.map((d,i)=>{const rebateScore=d.rebateMonthly?score({...d,monthlyPayment:d.rebateMonthly}):null;return <article className="deal" key={d.id}><div className="rank">#{i+1}</div>{d.imageUrl&&<img className="car" src={d.imageUrl} alt={`${d.year} ${d.brand} ${d.model}`}/>}<div className="deal-copy"><p className="location">{d.location}{d.expires?` · Expires ${d.expires}`:""}</p><h3>{d.year} {d.brand} {d.model}</h3><p className="trim">{d.trim}</p></div><div className="score"><b>{score(d).toFixed(2)}%</b><span>score</span>{rebateScore&&<><b className="rebate-score">{rebateScore.toFixed(2)}%</b><span className="rebate-label">with rebate</span></>}</div><div className="deal-data"><div><span>MSRP</span><b>{money(d.msrp)}</b></div><div><span>MONTHLY</span><b>{money(d.monthlyPayment)}</b></div><div><span>UPFRONT</span><b>{money(d.dueUpfront)}</b></div><div><span>TERM</span><b>{d.termMonths} mo</b></div></div>{d.incentive&&<p className="incentive">Conditional offer: {d.incentive}</p>}<div className="deal-footer"><span>{d.milesPerYear?`${d.milesPerYear.toLocaleString()} mi/yr`:"Mileage varies"}</span><a href={d.sourceUrl} target="_blank" rel="noreferrer">Leasehackr ↗</a></div></article>})}{visible.length<selected.length&&<button className="load-more" onClick={()=>setShown(n=>n+10)}>Load 10 more <span>{selected.length-visible.length} remaining</span></button>}</section>
  <div className={`bottom-actions ${showFloatingFilters?"visible":""}`}><button className="primary" onClick={()=>setFiltersOpen(true)}>Filters <span>{selected.length}</span></button></div>
  {filtersOpen&&<div className="sheet-backdrop" onMouseDown={()=>setFiltersOpen(false)}><section className="sheet" role="dialog" aria-modal="true" onMouseDown={e=>e.stopPropagation()}><div className="handle"/><div className="sheet-top"><div><h2>Filters</h2><p>Refine the selected state’s live offers.</p></div><button onClick={()=>setFiltersOpen(false)}>×</button></div><div className="range-fields">{([['msrp','MSRP',200000,1000],['monthly','Monthly payment',2500,25],['upfront','Upfront payment',15000,100],['miles','Expected miles / year',30000,500]] as const).map(([key,label,max,step])=>{const min=preferences[key].min, upper=preferences[key].max===limit?max:preferences[key].max;return <fieldset key={key}><legend>{label}</legend><div className="slider-label"><span>{min.toLocaleString()}</span><span>{preferences[key].max===limit?"Any":upper.toLocaleString()}</span></div><div className="dual-slider"><div className="slider-fill" style={{left:`${min/max*100}%`,right:`${100-upper/max*100}%`}}/><input aria-label={`${label} minimum`} type="range" min="0" max={max} step={step} value={min} onChange={e=>updateRange(key,'min',String(Math.min(+e.target.value,upper)))}/><input aria-label={`${label} maximum`} type="range" min="0" max={max} step={step} value={upper} onChange={e=>updateRange(key,'max',String(Math.max(+e.target.value,min)))}/></div></fieldset>})}</div><MultiPicker label="Brand" empty="All brands" options={allBrands} value={preferences.brands} onChange={brands=>{setPreferences(p=>({...p,brands,models:[],trims:[]}));setShown(10)}}/>{preferences.brands.length>0&&<MultiPicker label="Model" empty="All models" options={models} value={preferences.models} onChange={models=>{setPreferences(p=>({...p,models,trims:[]}));setShown(10)}}/>}{preferences.models.length>0&&<MultiPicker label="Trim" empty="All trims" options={trims} value={preferences.trims} onChange={trims=>{setPreferences(p=>({...p,trims}));setShown(10)}}/>}{preferences.brands.length>0&&!models.length&&<p className="no-trims">No current models for this brand. Applying the filter will show no results.</p>}<div className="sheet-actions"><button onClick={()=>{setPreferences(defaults);setShown(10)}}>Reset</button><button className="apply" onClick={()=>setFiltersOpen(false)}>Show {selected.length} deals</button></div></section></div>}
  {checkOpen&&<div className="sheet-backdrop" onMouseDown={()=>setCheckOpen(false)}><section className="sheet checker" role="dialog" aria-modal="true" onMouseDown={e=>e.stopPropagation()}><div className="handle"/><div className="sheet-top"><div><h2>External deal check</h2><p>Enter an offer to calculate its score and compare it with the current investigation.</p></div><button onClick={()=>setCheckOpen(false)}>×</button></div><div className="check-grid">{([['msrp','MSRP'],['upfront','Upfront payment'],['monthly','Monthly payment'],['term','Term (months)']] as const).map(([key,label])=><label key={key}>{label}<input type="number" inputMode="numeric" value={check[key]} onChange={e=>setCheck({...check,[key]:e.target.value})}/></label>)}</div>{checkScore&&<div className="check-result"><span>Your score</span><b>{checkScore.toFixed(2)}%</b><p>This scores better than {percentile}% of the {deals.length} live offers currently investigated.</p></div>}<button className="apply" onClick={()=>setCheckOpen(false)}>Done</button></section></div>}
  {compareOpen&&<div className="sheet-backdrop" onMouseDown={()=>setCompareOpen(false)}><section className="sheet compare-picker" role="dialog" aria-modal="true" onMouseDown={e=>e.stopPropagation()}><div className="handle"/><div className="sheet-top"><div><h2>Compare cars</h2><p>Build a short list of exact brand, model, and trim choices.</p></div><button onClick={()=>setCompareOpen(false)}>×</button></div><label className="select-label">Brand<select value={compareDraft.brand} onChange={e=>setCompareDraft({brand:e.target.value,model:"",trim:""})}><option value="">Choose a brand</option>{allBrands.map(b=><option key={b}>{b}</option>)}</select></label><label className="select-label">Model<select disabled={!compareDraft.brand} value={compareDraft.model} onChange={e=>setCompareDraft(d=>({...d,model:e.target.value,trim:""}))}><option value="">Choose a model</option>{draftModels.map(m=><option key={m}>{m}</option>)}</select></label><label className="select-label">Trim<select disabled={!compareDraft.model} value={compareDraft.trim} onChange={e=>setCompareDraft(d=>({...d,trim:e.target.value}))}><option value="">Choose a trim</option>{draftTrims.map(t=><option key={t}>{t}</option>)}</select></label><button className="add-choice" disabled={!compareDraft.trim} onClick={addCompareChoice}>Add to comparison</button>{compareChoices.length>0&&<div className="choice-list">{compareChoices.map(c=><div key={c.id}><span>{c.brand} {c.model}<small>{c.trim}</small></span><button aria-label={`Remove ${c.brand} ${c.model}`} onClick={()=>setCompareChoices(items=>items.filter(x=>x.id!==c.id))}>×</button></div>)}</div>}<button className="apply compare-go" disabled={!compareChoices.length} onClick={()=>{setCompareOpen(false);setCompareView(true)}}>Compare {compareChoices.length||""} car{compareChoices.length===1?"":"s"}</button></section></div>}
 </main>
}

function ComparePage({compared,region,onBack,onEdit}:{compared:Array<CompareChoice & {offer:Deal|undefined;specs:ReturnType<typeof roughSpecs>}>;region:string;onBack:()=>void;onEdit:()=>void}){
 const maxCost=Math.max(...compared.map(c=>c.offer?c.offer.monthlyPayment+c.offer.dueUpfront/c.offer.termMonths:0),1);
 return <main className="app-shell compare-page"><header className="compare-header"><button className="back" onClick={onBack}>← Deals</button><button className="outline" onClick={onEdit}>Edit cars</button></header><p className="eyebrow">Live Leasehackr comparison</p><h1>Compare prices</h1><p className="compare-subtitle">Best current {region==="All locations"?"US":""} offers for each selected trim, sorted by lease score.</p>{!compared.length?<div className="empty">Choose at least one car to begin comparing.</div>:<section className="cost-chart"><h2>Estimated monthly outlay</h2><p>Current Leasehackr offers, sorted by score. Outlay spreads the upfront payment over the lease term.</p>{compared.map(c=>{const total=c.offer?c.offer.monthlyPayment+c.offer.dueUpfront/c.offer.termMonths:0;return <div className="chart-row" key={c.id}><div className="chart-copy"><b>{c.brand} {c.model}</b><span>{c.trim}</span><small>{c.offer?.location||`No ${region==="All locations"?"live":"live in selected state"} deal`}</small></div>{c.offer?<div className="chart-detail"><i><em style={{width:`${total/maxCost*100}%`}}/></i><span>Live {money(c.offer.monthlyPayment)}/mo · Score {score(c.offer).toFixed(2)}% · MSRP {money(c.offer.msrp)} · Upfront {money(c.offer.dueUpfront)}</span></div>:<strong className="no-offer">No live deal</strong>} {c.offer&&<strong>{money(Math.round(total))}/mo</strong>}</div>})}</section>}</main>
}

function MultiPicker({label,empty,options,value,onChange}:{label:string;empty:string;options:string[];value:string[];onChange:(next:string[])=>void}){
 const summary=value.length?value.length===1?value[0]:`${value.length} selected`:empty;
 return <details className="multi-picker"><summary><span>{label}</span><b>{summary}</b></summary><div className="picker-options">{options.map(option=>{const active=value.includes(option);return <button type="button" className={active?"chosen":""} key={option} onClick={()=>onChange(active?value.filter(item=>item!==option):[...value,option])}>{active&&"✓ "}{option}</button>})}</div></details>
}
